cookie:
  expiry_days: 30
  key: signature_key
  name: auth_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$t8aDv8mc53JO6xKQeXHpPeTIGilNjWH6.FJKRKDFkNGUFZSMwTPqe
      role: admin
pre-authorized:
  emails: []
